SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `phonebook` (
  `id` int NOT NULL,
  `name` varchar(50) NOT NULL,
  `phone` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE `phonebook`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `phonebook`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=109;
COMMIT;
